"""empty message

Revision ID: 64b45a865a6d
Revises: d6045cf61215
Create Date: 2024-02-20 03:22:02.588360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b45a865a6d'
down_revision = 'd6045cf61215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
